//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.4-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.08 at 10:55:34 PM CET 
//


package eu.easyedu.robotj.ide.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.easyedu.robotj.ide.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RobotConfig_QNAME = new QName("http://robotj.easyedu.eu/schema/robotj-config", "robot-config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.easyedu.robotj.ide.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RobotObject }
     * 
     */
    public RobotObject createRobotObject() {
        return new RobotObject();
    }

    /**
     * Create an instance of {@link Resolution }
     * 
     */
    public Resolution createResolution() {
        return new Resolution();
    }

    /**
     * Create an instance of {@link DesktopConfig.Objects }
     * 
     */
    public DesktopConfig.Objects createDesktopConfigObjects() {
        return new DesktopConfig.Objects();
    }

    /**
     * Create an instance of {@link Color }
     * 
     */
    public Color createColor() {
        return new Color();
    }

    /**
     * Create an instance of {@link DesktopConfig }
     * 
     */
    public DesktopConfig createDesktopConfig() {
        return new DesktopConfig();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link RobotConfig }
     * 
     */
    public RobotConfig createRobotConfig() {
        return new RobotConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RobotConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://robotj.easyedu.eu/schema/robotj-config", name = "robot-config")
    public JAXBElement<RobotConfig> createRobotConfig(RobotConfig value) {
        return new JAXBElement<RobotConfig>(_RobotConfig_QNAME, RobotConfig.class, null, value);
    }

}
