//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.4-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.08 at 10:55:34 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://robotj.easyedu.eu/schema/robotj-config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.easyedu.robotj.ide.config;
