//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.4-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.01.08 at 10:55:34 PM CET
//


package eu.easyedu.robotj.ide.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RobotObject complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RobotObject">
 *   &lt;complexContent>
 *     &lt;extension base="{http://robotj.easyedu.eu/schema/robotj-config}DesktopObject">
 *       &lt;sequence>
 *         &lt;element name="color" type="{http://robotj.easyedu.eu/schema/robotj-config}Color"/>
 *         &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RobotObject", propOrder = {
    "color",
    "visible"
})
public class RobotObject extends DesktopObject {
    
    @XmlElement(required = true)
    protected Color color;
    @XmlElement(defaultValue = "true")
    protected Boolean visible;
    
    /**
     * Gets the value of the color property.
     *
     * @return
     *     possible object is
     *     {@link Color }
     *
     */
    public Color getColor() {
        return color;
    }
    
    /**
     * Sets the value of the color property.
     *
     * @param value
     *     allowed object is
     *     {@link Color }
     *
     */
    public void setColor(Color value) {
        this.color = value;
    }
    
    /**
     * Gets the value of the visible property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isVisible() {
        return visible;
    }
    
    /**
     * Sets the value of the visible property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }
    
}
